name: Build SavarezOS
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y live-build debootstrap

      - name: Fix Permissions
        run: chmod +x auto/config

      - name: Build ISO
        run: |
          sudo lb clean --purge
          rm -rf config/
          sudo lb config
          mkdir -p config/archives
          echo "deb http://deb.debian.org/debian/ bookworm main contrib non-free non-free-firmware" | sudo tee config/archives/debian.list.chroot
          echo "deb http://deb.debian.org/debian/ bookworm-updates main contrib non-free non-free-firmware" | sudo tee -a config/archives/debian.list.chroot
          sudo rm -f config/archives/ubuntu* sudo lb build

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SavarezOS-Alpha-ISO
          path: "*.iso"