name: Build SavarezOS
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
      options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies inside Debian container
        run: |
          apt-get update
          apt-get install -y live-build debootstrap squashfs-tools xorriso

      - name: Build ISO
        run: |
          lb clean --purge
          lb config noauto \
              --architecture amd64 \
              --distribution bookworm \
              --binary-images iso-hybrid \
              --archive-areas "main contrib non-free non-free-firmware"

          lb build

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SavarezOS-Alpha-ISO
          path: "*.iso"